import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { GOLDEN_FIXTURES } from "./goldens/fixtures.js";
import { runFixture, serializeGolden, expectedPath } from "./goldens/harness.js";

/**
 * Behavior-preservation gate for the simplify core (Invariant 1).
 *
 * Each fixture's simplified output is pinned as a committed golden. The carve
 * (restNodeToSnapshot → simplify) must reproduce every golden byte-for-byte;
 * any drift fails here. The comparison is an exact string `toBe` on insertion-
 * order JSON, so it gates key ORDER as well as structure — the bytes an LLM
 * actually receives. Goldens are explicit committed files regenerated by a
 * MANUAL script (`src/tests/goldens/regenerate.ts`) — deliberately NOT vitest's
 * auto-updating `toMatchSnapshot`, so a reflexive `-u` can never silently
 * re-baseline a regression and defeat the safety net.
 *
 * This is the STRICT byte-exact gate on the REST producer. The cross-producer
 * REST↔plugin parity harness (parity.test.ts) promotes these same goldens into
 * the shared target both producers must hit, comparing the SHARED SUBSET rather
 * than exact bytes so legitimate producer differences don't read as regressions.
 */
describe("simplify goldens", () => {
  for (const fixture of GOLDEN_FIXTURES) {
    it(`produces the committed golden for "${fixture.name}"`, async () => {
      const actual = serializeGolden(await runFixture(fixture));

      let expected: string;
      try {
        expected = readFileSync(expectedPath(fixture.name), "utf8");
      } catch {
        throw new Error(
          `Missing golden for "${fixture.name}". Run: pnpm tsx src/tests/goldens/regenerate.ts`,
        );
      }

      expect(actual).toBe(expected);
    });
  }
});
