import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { GOLDEN_FIXTURES } from "./goldens/fixtures.js";
import { runFixture, canonical, expectedPath } from "./goldens/harness.js";

/**
 * Behavior-preservation gate for the canonicalize carve (Invariant 1).
 *
 * Each fixture's simplified output is pinned as a committed golden. The carve
 * (restNodeToSnapshot → canonicalize) must reproduce every golden byte-for-byte;
 * any drift fails here. Goldens are explicit committed files regenerated by a
 * MANUAL script (`src/tests/goldens/regenerate.ts`) — deliberately NOT vitest's
 * auto-updating `toMatchSnapshot`, so a reflexive `-u` can never silently
 * re-baseline a regression and defeat the safety net.
 */
describe("canonicalize goldens", () => {
  for (const fixture of GOLDEN_FIXTURES) {
    it(`produces the committed golden for "${fixture.name}"`, async () => {
      const actual = canonical(await runFixture(fixture));

      let expected: unknown;
      try {
        expected = JSON.parse(readFileSync(expectedPath(fixture.name), "utf8"));
      } catch {
        throw new Error(
          `Missing golden for "${fixture.name}". Run: pnpm tsx src/tests/goldens/regenerate.ts`,
        );
      }

      expect(actual).toEqual(expected);
    });
  }
});
