# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install pnpm
RUN npm install -g pnpm

WORKDIR /app
# Copy project files
COPY . .

# Install deps and build
RUN pnpm install --frozen-lockfile
RUN pnpm build

# Production prune
ENV NODE_ENV=production
RUN pnpm prune --prod

# Use default entrypoint (no ENTRYPOINT), commands will be provided by Smithery
