// Generated by `pnpm docs:gen` (scripts/gen-flcm-doc.ts) — do not edit.
// Each entry is the marked region of examples/<id>.ts, extracted verbatim (and dedented) so the
// served example is byte-for-byte the code that type-checked. `pnpm docs:check` fails on drift.

export const EXAMPLE_CODE = {
  login: `const field = (key: string, label: string, placeholder: string) =>
  flcm.frame({ key, layout: { mode: "column", gap: 6 }, width: "fill" }, [
    flcm.text(label, {
      textStyle: { fontSize: 13, fontWeight: 500 },
      color: "rgba(255,255,255,0.7)",
    }),
    flcm.frame(
      {
        layout: { mode: "row", alignItems: "center", padding: { x: 16 } },
        width: "fill",
        height: 48,
        borderRadius: 12,
        fill: "rgba(255,255,255,0.06)",
        stroke: "rgba(255,255,255,0.12)",
        strokeWidth: 1,
      },
      [flcm.text(placeholder, { textStyle: { fontSize: 15 }, color: "rgba(255,255,255,0.4)" })],
    ),
  ]);

const screen = flcm.frame(
  {
    key: "login",
    name: "Login",
    layout: { mode: "column", gap: 28, padding: 32 },
    width: 390,
    height: 844,
    fill: "linear-gradient(180deg, #0B1020 0%, #131A2E 100%)",
  },
  [
    // Declared first → sits behind everything. Absolute, so it's out of the column flow.
    flcm.ellipse({
      name: "Glow",
      absolute: { x: -80, y: -60 },
      width: 180,
      height: 180,
      fill: "radial-gradient(circle, #2A3A66 0%, #0B102000 70%)",
      opacity: 0.6,
    }),
    flcm.text("Welcome back", {
      key: "title",
      color: "#FFFFFF",
      textStyle: { fontSize: 26, fontWeight: 700, letterSpacing: "-0.02em", lineHeight: "32px" },
    }),
    flcm.frame(
      {
        key: "card",
        name: "Card",
        layout: { mode: "column", gap: 16, padding: 28 },
        width: "fill",
        borderRadius: 20,
        fill: "rgba(255,255,255,0.04)",
        stroke: "rgba(255,255,255,0.08)",
        strokeWidth: 1,
        effects: flcm.effects({
          shadow: { y: 12, blur: 32, color: "rgba(0,0,0,0.18)" },
          backgroundBlur: 16,
        }),
      },
      [
        field("email", "Email", "you@example.com"),
        field("password", "Password", "••••••••"),
        flcm.frame(
          {
            key: "submit",
            name: "Submit",
            layout: { mode: "row", justifyContent: "center", alignItems: "center" },
            width: "fill",
            height: 48,
            borderRadius: 12,
            fill: "#6366F1",
          },
          [
            flcm.text("Sign in", {
              textStyle: { fontSize: 15, fontWeight: 600 },
              color: "#FFFFFF",
            }),
          ],
        ),
      ],
    ),
  ],
);

const out = await flcm.render(screen);

return {
  root: out.root.id, // the login frame's id
  card: out.keyed.card.id, // a keyed node, addressed after render
  title: out.keyed.title.text, // "Welcome back"
};`,
  caption: `// One text node, three styles: a colored @handle, plain body copy, a muted "more". The base props
// (size 15, a line height) apply to every run; each run overrides only what it changes.
const caption = flcm.text(
  [
    ["@ridgeline", { fontWeight: "semibold", color: "#6366F1" }],
    " summited at golden hour — the whole valley lit up. ",
    ["more", { color: "#8E8E93" }],
  ],
  {
    key: "caption",
    color: "#111827",
    width: 340,
    textStyle: { fontSize: 15, lineHeight: "20px" },
  },
);

const out = await flcm.render(caption);
return { caption: out.keyed.caption.id, text: out.keyed.caption.text };`,
  vector: `// A round "play" button: a themed circle, with a themeable play triangle (flcm.path) centered on top,
// and a brand mark pasted verbatim from SVG markup (flcm.svg) in the corner.
const player = flcm.frame({ width: 96, height: 96, borderRadius: 48, fill: "#111827" }, [
  // path themes like any primitive — the triangle fills with the accent color
  flcm.path({
    key: "play",
    d: "M38 30 L70 48 L38 66 Z",
    fill: "#6366F1",
    absolute: { x: 30, y: 24 },
  }),
  // svg pastes opaque markup (its colors are baked in — fill/stroke would be rejected here)
  flcm.svg('<svg viewBox="0 0 16 16"><circle cx="8" cy="8" r="6" fill="#22C55E"/></svg>', {
    width: 16,
    height: 16,
    absolute: { x: 8, y: 8 },
  }),
]);

const out = await flcm.render(player);
return { root: out.root.id, play: out.keyed.play.id };`,
  image: `// A feed post: a real photo as a rect fill, and a circular avatar as an ellipse filled with an image.
// flcm.image is a paint value — any shape carries one. The server fetches the bytes; your code doesn't.
const post = flcm.frame({ layout: { mode: "column", gap: 8 }, width: 390 }, [
  flcm.rect({ width: 390, height: 260, fill: flcm.image("https://example.com/photo.jpg") }),
  flcm.frame({ layout: { mode: "row", gap: 8, padding: 12, alignItems: "center" } }, [
    flcm.ellipse({
      width: 40,
      height: 40,
      fill: flcm.image("https://example.com/avatar.jpg", { scaleMode: "FILL" }),
    }),
    flcm.text("@ridgeline", { textStyle: { fontWeight: "semibold", fontSize: 14 } }),
  ]),
]);

const out = await flcm.render(post);
return out.root.id;`,
  reuse: `// Copy a card that already exists on the canvas into a different container, widened on the way.
// \`get\` reads it as the canonical shape; \`fromRead\` re-authors that shape through the constructors,
// which is what makes it a COPY. A bare read spec carries the original's live id, so passing one
// straight to \`append\` is refused rather than read as "move the node I just looked at".
const spec = await flcm.get("card");
const wider = flcm.fromRead({ ...spec, width: 480, name: "Card (wide)" });
const placed = await flcm.append("sidebar", wider);

// fromRead REBUILDS, so it reaches only what flcm can author: an INSTANCE, a stacked paint, or a grid
// container fails loud naming the field. flcm.clone(target, parent) duplicates the live node whole —
// faithful, but not editable as a spec first.
return placed;`,
} as const;
