import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import type { NodeSnapshot } from "@framelink/core/snapshot";

/**
 * Committed plan-neutral `NodeSnapshot[]` fixtures — one <name>.json per parity
 * case. This is the concrete target the read plan's `sceneNodeToSnapshot` aims
 * at: the plugin adapter must produce these snapshots (modulo the documented
 * shared-subset differences) for its output to match the goldens. Regenerated by
 * a MANUAL script (regenerate-snapshots.ts) from the REST decode, then gated
 * faithful by parity.test.ts — never auto-updated, mirroring the goldens' rule.
 */
export const SNAPSHOTS_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "snapshots");

export function snapshotPath(name: string): string {
  return path.join(SNAPSHOTS_DIR, `${name}.json`);
}

export function loadSnapshot(name: string): NodeSnapshot[] {
  return JSON.parse(readFileSync(snapshotPath(name), "utf8")) as NodeSnapshot[];
}
