// Regenerate (or drift-check) the two GENERATED flcm-docs artifacts from the same source the
// get_flcm_reference tool serves — so the doc a human reads in the repo, the strings the server
// ships, and the code that just type-checked are the same bytes:
//
//   • src/mcp/tools/flcm-docs/examples-code.generated.ts — the marked region of each worked example
//     (examples/<id>.ts), extracted verbatim. The examples stay real compile-checked .ts files; the
//     runtime imports these strings instead of reading source files, because the npm product runs
//     from a tsup bundle where sources aren't on disk.
//   • plugin/docs/authoring/flcm.md — the committed human-readable authoring doc, rendered by the
//     SAME generator that feeds the get_flcm_reference tool.
//
//   pnpm docs:gen     → write both
//   pnpm docs:check   → fail if either committed artifact is stale (wired into validate)
//
// The banner marks each file as generated; the doc body is buildFullReference() verbatim (the same
// content the reference tool serves section by section).

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const FLCM_DOCS_DIR = new URL("../src/mcp/tools/flcm-docs/", import.meta.url);
const DOC_PATH = fileURLToPath(new URL("../plugin/docs/authoring/flcm.md", import.meta.url));
const EXAMPLES_MODULE_PATH = fileURLToPath(new URL("examples-code.generated.ts", FLCM_DOCS_DIR));

// Keys double as file names: examples/<id>.ts. Adding an example = add the file, add its id here,
// add its title/intro in examples.ts, run docs:gen.
const EXAMPLE_IDS = ["login", "caption", "vector", "image"] as const;

const START = "// example:start";
const END = "// example:end";

// Pull the marked region out of an example file and dedent it to column 0. Markers are matched as
// whole lines (trimmed), so a stray mention of the token in prose can't be mistaken for a real
// marker. Fail loud if they're gone: a silently-empty example is exactly the stale-docs failure
// this generator exists to kill.
function extractExample(id: string): string {
  const path = fileURLToPath(new URL(`examples/${id}.ts`, FLCM_DOCS_DIR));
  const lines = readFileSync(path, "utf8").split("\n");
  const start = lines.findIndex((l) => l.trim() === START);
  const end = lines.findIndex((l) => l.trim() === END);
  if (start === -1 || end === -1 || end <= start) {
    throw new Error(
      `Cannot inline example: the ${START} / ${END} marker lines are missing or out of order in ${path}.`,
    );
  }
  return dedent(lines.slice(start + 1, end));
}

// Strip the common leading indentation (the region sits inside a function body) and trim blank edges.
function dedent(lines: string[]): string {
  const body = [...lines];
  while (body.length && body[0].trim() === "") body.shift();
  while (body.length && body[body.length - 1].trim() === "") body.pop();
  const indents = body.filter((l) => l.trim().length).map((l) => l.match(/^ */)![0].length);
  const min = indents.length ? Math.min(...indents) : 0;
  return body.map((l) => l.slice(min)).join("\n");
}

// Emit each example as a template literal (backslash-escaped) rather than a JSON one-liner: the
// generated module stays readable in diffs and stable under prettier, which never reformats
// template-literal contents.
function templateLiteral(code: string): string {
  return "`" + code.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";
}

function buildExamplesModule(): string {
  const entries = EXAMPLE_IDS.map((id) => `  ${id}: ${templateLiteral(extractExample(id))},`);
  return (
    "// Generated by `pnpm docs:gen` (scripts/gen-flcm-doc.ts) — do not edit.\n" +
    "// Each entry is the marked region of examples/<id>.ts, extracted verbatim (and dedented) so the\n" +
    "// served example is byte-for-byte the code that type-checked. `pnpm docs:check` fails on drift.\n" +
    "\n" +
    "export const EXAMPLE_CODE = {\n" +
    entries.join("\n") +
    "\n} as const;\n"
  );
}

// Provenance is a VISIBLE blockquote, not an HTML comment: the repo's hidden-char
// scanner rejects long HTML comments (a prompt-injection vector), and a human
// reading the rendered doc should see the "do not edit" warning anyway.
const BANNER =
  "> **Generated — do not edit.** Regenerate with `pnpm docs:gen`.\n" +
  "> Source: `plugin/src/preamble/schema.ts` (verbs/props) + `src/mcp/tools/flcm-docs/{narrative,examples}`.\n\n";

const mode = process.argv[2];
const expectedExamplesModule = buildExamplesModule();

if (mode === "check") {
  const actualModule = readFileSync(EXAMPLES_MODULE_PATH, "utf8");
  if (actualModule !== expectedExamplesModule) {
    console.error(
      `src/mcp/tools/flcm-docs/examples-code.generated.ts is stale — it no longer matches the ` +
        `marked regions of the example sources.\nRun \`pnpm docs:gen\` and commit the result.`,
    );
    process.exit(1);
  }
} else {
  writeFileSync(EXAMPLES_MODULE_PATH, expectedExamplesModule);
  console.log(`Wrote ${EXAMPLES_MODULE_PATH}`);
}

// Import the reference builders only now: they read the generated examples module, which the gen
// path just rewrote (and the check path just verified fresh) — a static import would render the
// doc from stale strings.
const { buildFullReference, buildQuickStart, buildReferenceSections } = await import(
  "../src/mcp/tools/flcm-docs/reference.js"
);

// Building the quick-start here (not just the full doc) makes its ≤2KB cap a validate-time gate: the
// call throws if the figma_execute_code description ever overflows, so `docs:check` fails rather than
// the server silently shipping a truncated contract.
buildQuickStart();

// Same idea for the get_flcm_reference size cap: render the ["all"] payload so an over-cap reference
// fails validate here, not at runtime as a silently-truncated tool result in an agent's context.
buildReferenceSections(["all"]);

const expected = BANNER + buildFullReference();

if (mode === "check") {
  const actual = readFileSync(DOC_PATH, "utf8");
  if (actual !== expected) {
    console.error(
      `plugin/docs/authoring/flcm.md is stale — it no longer matches the generated reference.\n` +
        `Run \`pnpm docs:gen\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log("flcm docs are in sync with the schema.");
} else {
  writeFileSync(DOC_PATH, expected);
  console.log(`Wrote ${DOC_PATH}`);
}
